import React, { useContext } from "react";
import Head from "next/head";
import Settings from "../components/Settings";
import styles from "../styles/Home.module.css";
import { AppContext } from "../context/context";
import Map from "../components/Map";
import ListItem from "../components/ListItem";
import ListComponent from "../components/ListComponent";

export default function Home() {
  const { showSettings, sortSelection, fetchInterval, mapView } = useContext(AppContext);
  return (
    <div className={styles.container}>
      <Head>
        <title>Jarlskjálfti</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.container}>

       {showSettings&& <Settings />}
      {mapView? <Map /> : <ListComponent/>}
      </section>
    </div>
  );
}
